'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class children_create_shp_list

    '''<summary>
    '''lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_list_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_list_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_listName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_listName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_estimated_budget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_estimated_budget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_estimated_butget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_estimated_butget As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_for_budget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_for_budget As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_date_created control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_date_created As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_date_created control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_date_created As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_finish_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_finish_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_finish_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_finish_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_for_finishDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_for_finishDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''btn_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_for_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_for_all As Global.System.Web.UI.WebControls.Label
End Class
