'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class family_shop_list_form

    '''<summary>
    '''lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu1 As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''View_private_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View_private_list As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''GridView_private_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_private_list As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Btn_delete_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_delete_list As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_share_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_share_list As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_view_by_cat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_view_by_cat As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_search As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_search As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_search_private_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_search_private_list As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panel_share_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_share_to As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_share_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_share_to As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_share_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_share_to As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_share_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_share_to As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_share_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_share_to As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panel_list_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_list_detail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''link_add_new_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_add_new_product As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_add_new_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_add_new_product As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Select_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Select_product As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_select_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_select_product As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_new_prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_new_prod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_new_prob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_new_prob As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_new_pro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_new_pro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_add_new_prd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_add_new_prd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_add_unit_price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_unit_price As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_unit_price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_unit_price As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_for_unitP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_for_unitP As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_add_quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_quantity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_quantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_for_quan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_for_quan As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_category_select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_category_select As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_category_select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_category_select As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_new_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_new_category As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_new_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_new_category As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_new_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_new_category As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_check_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_check_category As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_add_new_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_new_product As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridView_list_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_list_detail As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_delete_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_delete_product As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_mark_purchased control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_mark_purchased As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btn_check_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_check_total As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_cost_msg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cost_msg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_total_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_total_cost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_sort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_sort As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_sort_detail_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_sort_detail_list As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_sort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_sort As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_search_detail_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_search_detail_list As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_search_detail_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_search_detail_list As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_search_detail_ist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_search_detail_ist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_download_excel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_download_excel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_sorting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_sorting As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_validation_detail_lst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_detail_lst As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_validation_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_all As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''View_shared_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View_shared_list As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_shared_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_shared_by As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_shared_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_shared_by As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_save_shared_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_shared_by As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_share_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_share_by As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_shared_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_shared_to As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_shared_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_shared_to As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''panel_shared_to_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_shared_to_product As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grid_view_share_to_pro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_view_share_to_pro As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''View_old_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View_old_list As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''GridView_old_main_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_old_main_list As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_restore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_restore As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridView_sub_old_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_sub_old_list As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''View_manage_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View_manage_product As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_mgt_all_not_pur_prods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_mgt_all_not_pur_prods As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_mark_pur_mgt_all_prd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_mark_pur_mgt_all_prd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_delete_pur_mgt_all_prd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_delete_pur_mgt_all_prd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtbx_update_quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_update_quantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_update_quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update_quantity As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_update_quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_update_quantity As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtbx_update_price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_update_price As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_update_price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update_price As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_update_price control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_update_price As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtbx_search_mgt_all_prd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_search_mgt_all_prd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_search_mgt_all_prd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_search_mgt_all_prd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_subtitle3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_purchased_product control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_purchased_product As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btn_mark_as_not_purchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_mark_as_not_purchase As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_delete_purchased_prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_delete_purchased_prod As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtbx_update_quantity_purchased_prd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_update_quantity_purchased_prd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_update_quantity_purchased_prd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update_quantity_purchased_prd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_update_quan_purchased_prd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_update_quan_purchased_prd As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtbx_update_price_purchased_prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_update_price_purchased_prod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_update_price_purchased_prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update_price_purchased_prod As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_update_price_purchased_prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_update_price_purchased_prod As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtbx_search_purchased_prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_search_purchased_prod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_search_purchased_prod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_search_purchased_prod As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view4_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view4_1 As Global.System.Web.UI.WebControls.Label
End Class
