'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class family_add_move_asset

    '''<summary>
    '''lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_select_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_select_location As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_select_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_select_location As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_location As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_location As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_location As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_item_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_item_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_item_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_item_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_select_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_select_category As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_select_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_select_category As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_category As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_category As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_category As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_retailer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_retailer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_retailer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_retailer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_current_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_current_value As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_current_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_current_value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_current_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_current_value As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_purchase_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_purchase_cost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_purchase_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_purchase_cost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_purchase_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_purchase_cost As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_purchse_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_purchse_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_purchase_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_purchase_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_purchase_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_purchase_date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_purchase_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_purchase_method As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_select_purchase_mathod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_select_purchase_mathod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_purchase_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_purchase_method As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_purchase_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_purchase_method As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_purchase_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_purchase_method As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_quantity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_quantity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_quantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_quantity As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_make control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_make As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_make control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_make As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_model As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_model As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_serial_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_serial_num As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_serial_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_serial_num As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_warranty_period control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_warranty_period As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_warranty_period control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_warranty_period As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_warranty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_warranty As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_notes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_notes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FileUpload_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload_img As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''validation_uload_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_uload_img As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btn_upload_pic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_upload_pic As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Repeater_preview_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater_preview_img As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btn_save_move_asset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_move_asset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation As Global.System.Web.UI.WebControls.Label
End Class
