'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class guest_register_form

    '''<summary>
    '''lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''username_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents username_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''username_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents username_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''suggestion_pnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestion_pnl As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''check_user_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_user_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''suggest_username_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggest_username_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''check_user_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_user_val As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''checkuser_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkuser_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''req_username_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents req_username_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''email_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''email_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''req_email_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents req_email_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''regEx_email_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regEx_email_val As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''password_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents password_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''password_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents password_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''req_password_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents req_password_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''confirm_password_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirm_password_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''confirm_password_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirm_password_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''confirm_req_pass_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirm_req_pass_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''comp_password_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_password_val As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''question_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents question_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''question_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents question_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''answer_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents answer_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''answer_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents answer_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Req_answer_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Req_answer_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''term_condition_ckbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents term_condition_ckbx As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''termNcond_hlink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents termNcond_hlink As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''register_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents register_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation As Global.System.Web.UI.WebControls.Label
End Class
