'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class member_online_activation

    '''<summary>
    '''lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''view_check_secret_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view_check_secret_code As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_activation_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_activation_code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_activation_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_activation_code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_activation_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_activation_code As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_subtitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_resent_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_resent_code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_resent_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_resent_code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_resent_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_resent_code As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_offline_activation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_offline_activation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''validation_mail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_mail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''view_offline_activation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view_offline_activation As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_offline_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_offline_username As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_offline_username control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_offline_username As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_offline_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_offline_email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_offline_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_offline_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_offline_mail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_offline_mail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_offline_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_offline_password As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_offline_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_offline_password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_view_offfline_activation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_view_offfline_activation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''view_change_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view_change_password As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_new_passwrod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_new_passwrod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_new_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_new_password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_confrm_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_confrm_password As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_confirm_passwrd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_confirm_passwrd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_compare_passwrod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_compare_passwrod As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''btn_change_password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_change_password As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''View_answer_question control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View_answer_question As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_question control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_question As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_question control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_question As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_answer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_answer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_answer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_answer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_activate_acct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_activate_acct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view4 As Global.System.Web.UI.WebControls.Label
End Class
