'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class member_addfamily_form

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''username_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents username_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''username_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents username_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''suggestion_pnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestion_pnl As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''check_user_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_user_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''suggest_username_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggest_username_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''checkuser_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkuser_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''req_username_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents req_username_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''email_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''email_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''req_mail_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents req_mail_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''requ_exp_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requ_exp_email As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''password_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents password_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''password_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents password_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''req_password_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents req_password_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lbl_comfirm_pwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_comfirm_pwd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_confirm_pwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_confirm_pwd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmpPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmpPwd As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''relationship_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents relationship_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''relationship_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents relationship_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''name_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents name_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''name_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents name_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''req_name_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents req_name_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RegularExpressionValidator_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_name As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''surname_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surname_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''surname_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surname_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator_surname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_surname As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''gender_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gender_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gender_ddl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gender_ddl As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dob_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dob_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dob_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dob_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''req_dob_val control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents req_dob_val As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''validation_for_dob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_for_dob As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''mobilenum_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobilenum_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mobilenum_txtbx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobilenum_txtbx As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator_phoneNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator_phoneNum As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''register_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents register_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_check As Global.System.Web.UI.WebControls.Label
End Class
