'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class member_edit_loan_form

    '''<summary>
    '''lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScriptManager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager2 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel18 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''GridView_select_loan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_select_loan As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_subtitle_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle_1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu1 As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''lennder_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lennder_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle_2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''link_lendername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_lendername As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_lender_name_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_lender_name_edit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_lender_name_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_name_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_name_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_name_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_lender_name_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_lender_name_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link_lenderDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_lenderDescription As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_lender_descrip_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_lender_descrip_edit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_lender_decsrip_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_decsrip_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_descrip_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_descrip_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_lender_descrip_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_lender_descrip_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link_lendermail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_lendermail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_lendermail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_lendermail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_lender_mail_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_mail_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_mail_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_mail_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_lender_mail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_lender_mail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_lender_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_lender_email As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''link_lendertype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_lendertype As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_lender_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_lender_type As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_lender_type_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_type_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_lender_type_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_lender_type_edit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_save_lender_type_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_lender_type_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_add_new_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_new_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_new_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_new_type As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_new_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_new_type As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link_lenderlocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_lenderlocation As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_lender_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_lender_location As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_lender_street_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_street_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_street_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_street_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_lender_town_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_town_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_town_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_town_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_lender_town control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_lender_town As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_lender_country_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_country_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_country_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_country_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_lender_country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_lender_country As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_lender_postal_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_postal_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_postal_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_postal_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_postal_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_postal_code As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btn_save_lender_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_lender_location As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link_lender_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_lender_contact As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_lender_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_lender_contact As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_lender_phn_fix_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_phn_fix_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_phn_fix_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_phn_fix_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_phn_fix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_phn_fix As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_lender_phn_ptb_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_phn_ptb_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_phn_ptb_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_phn_ptb_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_phn_ptb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_phn_ptb As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_lender_fax_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_fax_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_fax_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_fax_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_fax As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_lender_website_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_lender_website_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_lender_website_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_lender_website_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_lender_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_lender_contact As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''loan_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loan_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle_3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''link_loan_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_loan_name As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_loan_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_loan_name As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_loan_name_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_loan_name_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_loan_name_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_loan_name_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_loan_name_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_loan_name_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link_loantype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_loantype As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_loan_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_loan_type As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_loan_type_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_loan_type_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_loan_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_loan_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_save_loan_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_loan_type As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_add_loan_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_loan_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_loan_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_loan_type As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_loan_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_loan_type As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link_loandetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_loandetail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_loandetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_loandetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_loan_detail_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_loan_detail_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_loan_detail_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_loan_detail_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_loan_detail_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_loan_detail_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_amount As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_loan_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_loan_amount As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_loan_amount_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_loan_amount_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_loan_amount_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_loan_amount_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_loan_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_loan_amount As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_loan_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_loan_amount As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''link_interest_rate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_interest_rate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_interest_rate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_interest_rate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_loan_inrst_rate_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_loan_inrst_rate_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_interest_rate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_interest_rate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_loan_inrst_rate_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_loan_inrst_rate_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_intrest_rate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_intrest_rate As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''link_date_taken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_date_taken As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_date_taken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_date_taken As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_loan_date_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_loan_date_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_loan_date_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_loan_date_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_loan_date_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_loan_date_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_date_taken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_date_taken As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''link_loan_term control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_loan_term As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_loan_term control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_loan_term As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_loan_term_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_loan_term_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_loan_term_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_loan_term_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_loan_term_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_loan_term_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''validation_loan_term control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_loan_term As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''link_guarantor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_guarantor As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_guarantor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_guarantor As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_guarantor_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_guarantor_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_guarantor_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_guarantor_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_guarantor_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_guarantor_edit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''link_mortgage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents link_mortgage As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''panel_mortgage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_mortgage As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_mortgage_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_mortgage_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_mortgage_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_mortgage_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_mortgage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_mortgage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''repayment_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repayment_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle_4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_loan_repayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_loan_repayment As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_repay_capital_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_repay_capital_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_repy_capital_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_repy_capital_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_repay_capital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_repay_capital As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_repay_interst_paid_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_repay_interst_paid_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_repay_interest_paid_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_repay_interest_paid_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_repay_intrst_paid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_repay_intrst_paid As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_repay_intrst_rate_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_repay_intrst_rate_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_repay_intrst_rate_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_repay_intrst_rate_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_repay_intrst_rate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_repay_intrst_rate As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_repay_date_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_repay_date_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_repay_date_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_repay_date_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_repay_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_repay_date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_repay_remark_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_repay_remark_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_repay_remark_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_repay_remark_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_save_repay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_repay As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view3 As Global.System.Web.UI.WebControls.Label
End Class
