'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class member_add_insurance

    '''<summary>
    '''Lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''company_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_company_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_company_descrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_descrip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_compnay_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_compnay_description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_branch_of control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_branch_of As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_branch_of control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_branch_of As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_company_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_email As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_company_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_street As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_comapny_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_comapny_street As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_company_town control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_town As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_town control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_town As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_town control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_town As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_company_country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_country As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_country As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_country As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_compnay_phne_fix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_compnay_phne_fix As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_phn_fix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_phn_fix As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_phn_fix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_phn_fix As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_company_phne_ptb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_phne_ptb As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_phne_ptb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_phne_ptb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_phn_ptb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_phn_ptb As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_fax As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_company_website control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_website As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_website control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_website As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_next_to_policy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_next_to_policy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''policiy_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents policiy_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_insurance_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_insurance_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_insurance_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_insurance_type As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_insurance_type As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_policy_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_num As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_policy_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_policy_number As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_policy_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_policy_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_policy_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_policy_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_description As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtxbx_policy_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtxbx_policy_description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_policy_effec_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_effec_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_policy_effec_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_policy_effec_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_effec_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_effec_date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_policy_expiry_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_expiry_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_policy_expiry_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_policy_expiry_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_expiry_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_expiry_date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''btn_prev_to_company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_prev_to_company As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_next_to_cover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_next_to_cover As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cover_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cover_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lbl_subtitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_subtitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cover_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_cover_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_cover_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_cover_type As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_cover_type As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_cover_descrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cover_descrip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_cover_descri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_cover_descri As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_insured_obj_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_insured_obj_person As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_insured_obj_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_insured_obj_person As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_beneficiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_beneficiary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_amount_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_amount_beneficiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_amount_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_amount_beneficiary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_amount_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_amount_beneficiary As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_cover_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cover_fees As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_cover_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_cover_fees As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_cover_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_cover_fees As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_doc_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_doc_fees As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_doc_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_doc_fees As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_doc_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_doc_fees As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_agent_commision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_agent_commision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_agent_commission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_agent_commission As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_agent_com control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_agent_com As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Panel_vehicle_cover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_vehicle_cover As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_reg_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_reg_num As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_reg_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_reg_num As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_manufacturer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_manufacturer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_manufacturer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_manufacturer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_serial_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_serial_num As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_serial_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_serial_num As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FileUpload_picture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload_picture As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''validation_upload_pic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_upload_pic As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''Repeater_diaplay_pic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater_diaplay_pic As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btn_prev_policy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_prev_policy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_save_insurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_insurance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view3 As Global.System.Web.UI.WebControls.Label
End Class
