'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class member_edit_insurance

    '''<summary>
    '''lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''GridView_select_insurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_select_insurance As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Menu1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Menu1 As Global.System.Web.UI.WebControls.Menu

    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''company_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_company_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_company_detail As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_company_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_company_descrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_descrip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_compnay_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_compnay_description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_branch_of control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_branch_of As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_branch_of control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_branch_of As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_company_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_email As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_company_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_street As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_comapny_street control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_comapny_street As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_company_town control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_town As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_town control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_town As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_town control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_town As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_company_country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_country As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_country As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_country As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_compnay_phne_fix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_compnay_phne_fix As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_phn_fix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_phn_fix As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_phn_fix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_phn_fix As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_company_phne_ptb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_phne_ptb As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_company_phne_ptb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_company_phne_ptb As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_phn_ptb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_phn_ptb As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_fax As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_fax As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_company_website control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_company_website As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_website control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_website As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_update_comapny control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update_comapny As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''policy_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents policy_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_policy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_policy As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_insurance_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_insurance_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_insurance_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_insurance_type As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_insurance_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_insurance_type As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_policy_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_num As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_policy_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_policy_number As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_policy_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_policy_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_policy_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_policy_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_description As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtxbx_policy_description control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtxbx_policy_description As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_policy_effec_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_effec_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_policy_effec_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_policy_effec_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_effec_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_effec_date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_policy_expiry_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_policy_expiry_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_policy_expiry_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_policy_expiry_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_expiry_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_expiry_date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''btn_update_policy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update_policy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cover_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cover_view As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_cover_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_cover_detail As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gridview_preview_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridview_preview_img As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cover_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_cover_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_cover_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_cover_type As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_cover_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_cover_type As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_cover_descrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cover_descrip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_cover_descri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_cover_descri As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_insured_obj_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_insured_obj_person As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_insured_obj_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_insured_obj_person As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_beneficiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_beneficiary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_amount_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_amount_beneficiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_amount_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_amount_beneficiary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_amount_beneficiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_amount_beneficiary As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_cover_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_cover_fees As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_cover_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_cover_fees As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_cover_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_cover_fees As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_doc_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_doc_fees As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_doc_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_doc_fees As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_doc_fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_doc_fees As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_agent_commision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_agent_commision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_agent_commission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_agent_commission As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_agent_com control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_agent_com As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_reg_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_reg_num As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_reg_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_reg_num As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_manufacturer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_manufacturer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_manufacturer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_manufacturer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_serial_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_serial_num As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_serial_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_serial_num As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_update_cover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update_cover As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''repayment_View control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repayment_View As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_repayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_repayment As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbl_due_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_due_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_due_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_due_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_due_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_due_date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_total_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_total_amount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_total_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_total_amount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_total_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_total_amount As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_amount_paid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_amount_paid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_amount_paid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_amount_paid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_amount_paid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_amount_paid As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_amount_remain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_amount_remain As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_amount_remain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_amount_remain As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_amount_remain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_amount_remain As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btn_update_repayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_update_repayment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_view4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_view4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_edit_cover_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_edit_cover_img As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView_edit_cover_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_edit_cover_img As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''FileUpload_picture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload_picture As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btn_upload_cover_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_upload_cover_img As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_close_panel_view_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_close_panel_view_img As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rexp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rexp As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_validation_upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_upload As Global.System.Web.UI.WebControls.Label
End Class
