'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class member_add_immova_property

    '''<summary>
    '''lbl_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_title As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_item_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_item_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_item_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_item_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_select_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_select_category As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_select_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_select_category As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_category As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_category As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_category As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_location As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_location As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_current_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_current_value As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_current_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_current_value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_current_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_current_value As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_purchase_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_purchase_cost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_purchase_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_purchase_cost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_purchase_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_purchase_cost As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_purchse_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_purchse_date As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_purchase_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_purchase_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_purchase_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_purchase_date As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lbl_purchase_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_purchase_method As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_select_purchase_mathod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_select_purchase_mathod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_add_purchase_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_purchase_method As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_add_purchase_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_add_purchase_method As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_purchase_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_purchase_method As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_length control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_length As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_length control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_length As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_length control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_length As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_width As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_width As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_width As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_notes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_notes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_no_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_no_room As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_no_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_no_room As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_no_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_no_room As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_add_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_add_room As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_open_panel_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_open_panel_room As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_open_uploader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_open_uploader As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_all_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_all_room As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_all_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_all_room As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FileUpload_prperty_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload_prperty_img As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''validation_property_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_property_img As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btn_upload_property_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_upload_property_img As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_property_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_property_img As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Repeater_property_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater_property_img As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btn_add_property control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_property As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_cancel_save_property control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancel_save_property As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_room As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_room_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_room_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_room_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_room_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_room_length control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_room_length As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_room_length control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_room_length As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_room_length control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_room_length As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_room_width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_room_width As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_room_width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_room_width As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''validation_room_width control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_room_width As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbl_room_note control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_room_note As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbx_room_note control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbx_room_note As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_add_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_room As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_close_panel_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_close_panel_room As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_room As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_uploader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_uploader As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''GridView_select_room control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView_select_room As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''FileUpload_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload_img As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''validation_uload_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents validation_uload_img As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btn_upload_pic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_upload_pic As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_close_uploader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_close_uploader As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_validation_uploader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_validation_uploader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Repeater_preview_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater_preview_img As Global.System.Web.UI.WebControls.Repeater
End Class
